site_name: ExaMon
theme:
  name: material
  features:
    - toc.follow
markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
nav:
    - Home: "index.md"
    - Intruduction: "Introduction.md"
    - Administrators: Administrators/
    - Users: Users/
    - Metric Reference: "Metric_reference.md"
    - About: "About.md"


