site_name: ExaMon
theme:
  name: material
  features:
    - toc.follow
markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
nav:
    - Home: "index.md"
    - Introduction: "Introduction.md"
    - Administrators:
      - Getting started: Administrators/Getting_started.md
    - Users:
      - Getting started: Users/Getting_started.md
    - Metrics Reference: "Metrics_reference.md"
    - About: "About.md"


