site_name: ExaMon
repo_url: https://github.com/EEESlab/examon
repo_name: EEESlab/examon
site_description: Gain deeper insights into your data with advanced monitoring, analytics and visualization tools.
# copyright: Copyright &copy; 2023 Francesco Beneventi

theme:
  name: material
  custom_dir: overrides
  features:
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  logo: assets/images/favicon.png
  plugins:
    - search:
        lang: en
        prebuild_index: true

plugins:
  - blog
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Home: "index.md"
    - Getting started: "getting_started.md"
    - Introduction: "Introduction.md"
    - Administrators:
      - Getting started: Administrators/Getting_started.md
    - Users:
      - Getting started: Users/Getting_started.md
    - Metrics Reference: "Metrics_reference.md"
    - About: "About.md"
    - Credits: "credits.md"
    - Contact Us: "contactus.md"
    - Blog:
      - blog/index.md


