name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mike

      - name: Set release version
        run: echo "GIT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build and deploy documentation using token
        run: poetry run mike deploy --push --update-aliases ${GIT_TAG} latest